title: Tejas Narayan
email: tejas@narayan.dev
description: >- # this means to ignore newlines until "baseurl:"
  My name is Tejas Narayan, I'm looking for opportunities in HealthTech or EdTech in NYC for when I graduate in Oct 2022.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "tjsnryn.dev" # the base hostname & protocol for your site, e.g. http://example.com
github_username:       tjsnryn

logo_url:              https://avatars.githubusercontent.com/u/7364824?v=4

permalink:             /:title # Post permalink
mathjax:               true  # enables support for mathjax - set to 'false' to disable
social_share_previews: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-redirect-from
  - jekyll-sitemap

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script" ]

remote_theme: mmistakes/minimal-mistakes
